/* Generated by integration/wasi/generate.py; do not hand-edit. */
#include "dotnet_pal.h"
_Static_assert(sizeof(void*) == 4, "WASI bridge requires wasm32");
static uint32_t call(uint32_t op, const uint64_t *args, uint32_t count) {
    const dotnet_pal_api *api = dotnet_pal_get_api(DOTNET_PAL_ABI_VERSION);
    if (!api || api->header.struct_size < DOTNET_PAL_WASI_API_SIZE || !(api->header.capabilities & DOTNET_PAL_CAP_WASI_DISPATCH) || !api->wasi.invoke) return 52;
    return api->wasi.invoke(op, args, count);
}
uint32_t __imported_wasi_snapshot_preview1_args_get(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(0u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_args_sizes_get(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(1u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_environ_get(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(2u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_environ_sizes_get(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(3u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_clock_res_get(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(4u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_clock_time_get(uint32_t a0, uint64_t a1, uint32_t a2) {
    const uint64_t args[] = {a0, a1, a2};
    return call(5u, args, 3u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_advise(uint32_t a0, uint64_t a1, uint64_t a2, uint32_t a3) {
    const uint64_t args[] = {a0, a1, a2, a3};
    return call(6u, args, 4u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_allocate(uint32_t a0, uint64_t a1, uint64_t a2) {
    const uint64_t args[] = {a0, a1, a2};
    return call(7u, args, 3u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_close(uint32_t a0) {
    const uint64_t args[] = {a0};
    return call(8u, args, 1u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_datasync(uint32_t a0) {
    const uint64_t args[] = {a0};
    return call(9u, args, 1u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_fdstat_get(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(10u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_fdstat_set_flags(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(11u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_fdstat_set_rights(uint32_t a0, uint64_t a1, uint64_t a2) {
    const uint64_t args[] = {a0, a1, a2};
    return call(12u, args, 3u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_filestat_get(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(13u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_filestat_set_size(uint32_t a0, uint64_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(14u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_filestat_set_times(uint32_t a0, uint64_t a1, uint64_t a2, uint32_t a3) {
    const uint64_t args[] = {a0, a1, a2, a3};
    return call(15u, args, 4u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_pread(uint32_t a0, uint32_t a1, uint32_t a2, uint64_t a3, uint32_t a4) {
    const uint64_t args[] = {a0, a1, a2, a3, a4};
    return call(16u, args, 5u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_prestat_get(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(17u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_prestat_dir_name(uint32_t a0, uint32_t a1, uint32_t a2) {
    const uint64_t args[] = {a0, a1, a2};
    return call(18u, args, 3u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_pwrite(uint32_t a0, uint32_t a1, uint32_t a2, uint64_t a3, uint32_t a4) {
    const uint64_t args[] = {a0, a1, a2, a3, a4};
    return call(19u, args, 5u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_read(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) {
    const uint64_t args[] = {a0, a1, a2, a3};
    return call(20u, args, 4u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_readdir(uint32_t a0, uint32_t a1, uint32_t a2, uint64_t a3, uint32_t a4) {
    const uint64_t args[] = {a0, a1, a2, a3, a4};
    return call(21u, args, 5u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_renumber(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(22u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_seek(uint32_t a0, uint64_t a1, uint32_t a2, uint32_t a3) {
    const uint64_t args[] = {a0, a1, a2, a3};
    return call(23u, args, 4u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_sync(uint32_t a0) {
    const uint64_t args[] = {a0};
    return call(24u, args, 1u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_tell(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(25u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_fd_write(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) {
    const uint64_t args[] = {a0, a1, a2, a3};
    return call(26u, args, 4u);
}
uint32_t __imported_wasi_snapshot_preview1_path_create_directory(uint32_t a0, uint32_t a1, uint32_t a2) {
    const uint64_t args[] = {a0, a1, a2};
    return call(27u, args, 3u);
}
uint32_t __imported_wasi_snapshot_preview1_path_filestat_get(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) {
    const uint64_t args[] = {a0, a1, a2, a3, a4};
    return call(28u, args, 5u);
}
uint32_t __imported_wasi_snapshot_preview1_path_filestat_set_times(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint64_t a4, uint64_t a5, uint32_t a6) {
    const uint64_t args[] = {a0, a1, a2, a3, a4, a5, a6};
    return call(29u, args, 7u);
}
uint32_t __imported_wasi_snapshot_preview1_path_link(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5, uint32_t a6) {
    const uint64_t args[] = {a0, a1, a2, a3, a4, a5, a6};
    return call(30u, args, 7u);
}
uint32_t __imported_wasi_snapshot_preview1_path_open(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint64_t a5, uint64_t a6, uint32_t a7, uint32_t a8) {
    const uint64_t args[] = {a0, a1, a2, a3, a4, a5, a6, a7, a8};
    return call(31u, args, 9u);
}
uint32_t __imported_wasi_snapshot_preview1_path_readlink(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) {
    const uint64_t args[] = {a0, a1, a2, a3, a4, a5};
    return call(32u, args, 6u);
}
uint32_t __imported_wasi_snapshot_preview1_path_remove_directory(uint32_t a0, uint32_t a1, uint32_t a2) {
    const uint64_t args[] = {a0, a1, a2};
    return call(33u, args, 3u);
}
uint32_t __imported_wasi_snapshot_preview1_path_rename(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) {
    const uint64_t args[] = {a0, a1, a2, a3, a4, a5};
    return call(34u, args, 6u);
}
uint32_t __imported_wasi_snapshot_preview1_path_symlink(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) {
    const uint64_t args[] = {a0, a1, a2, a3, a4};
    return call(35u, args, 5u);
}
uint32_t __imported_wasi_snapshot_preview1_path_unlink_file(uint32_t a0, uint32_t a1, uint32_t a2) {
    const uint64_t args[] = {a0, a1, a2};
    return call(36u, args, 3u);
}
uint32_t __imported_wasi_snapshot_preview1_poll_oneoff(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3) {
    const uint64_t args[] = {a0, a1, a2, a3};
    return call(37u, args, 4u);
}
void __imported_wasi_snapshot_preview1_proc_exit(uint32_t a0) {
    const uint64_t args[] = {a0};
    (void)call(38u, args, 1u); __builtin_trap();
}
uint32_t __imported_wasi_snapshot_preview1_sched_yield(void) {
    return call(39u, NULL, 0u);
}
uint32_t __imported_wasi_snapshot_preview1_random_get(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(40u, args, 2u);
}
uint32_t __imported_wasi_snapshot_preview1_sock_accept(uint32_t a0, uint32_t a1, uint32_t a2) {
    const uint64_t args[] = {a0, a1, a2};
    return call(41u, args, 3u);
}
uint32_t __imported_wasi_snapshot_preview1_sock_recv(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, uint32_t a5) {
    const uint64_t args[] = {a0, a1, a2, a3, a4, a5};
    return call(42u, args, 6u);
}
uint32_t __imported_wasi_snapshot_preview1_sock_send(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) {
    const uint64_t args[] = {a0, a1, a2, a3, a4};
    return call(43u, args, 5u);
}
uint32_t __imported_wasi_snapshot_preview1_sock_shutdown(uint32_t a0, uint32_t a1) {
    const uint64_t args[] = {a0, a1};
    return call(44u, args, 2u);
}
