#!/usr/bin/env python3
"""Generate the raw WASIp1 libc thunks and Rust signature guards from one schema.
The SDK archive ABI link test must be run; public wasi/api.h path helpers have
additional implicit string lengths and are not raw import signatures.
"""
import argparse, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
def outputs():
    schema=json.loads((ROOT/"integration/wasi/schema.json").read_text())
    operations=schema["operations"]
    if len(operations)!=45 or [x["opcode"] for x in operations]!=list(range(45)): raise ValueError("invalid opcode set")
    c=['/* Generated by integration/wasi/generate.py; do not hand-edit. */', '#include "dotnet_pal.h"',
       '_Static_assert(sizeof(void*) == 4, "WASI bridge requires wasm32");',
       'static uint32_t call(uint32_t op, const uint64_t *args, uint32_t count) {',
       '    const dotnet_pal_api *api = dotnet_pal_get_api(DOTNET_PAL_ABI_VERSION);',
       '    if (!api || api->header.struct_size < DOTNET_PAL_WASI_API_SIZE || !(api->header.capabilities & DOTNET_PAL_CAP_WASI_DISPATCH) || !api->wasi.invoke) return 52;',
       '    return api->wasi.invoke(op, args, count);', '}']
    rs=['// Generated by integration/wasi/generate.py; do not hand-edit.', 'pub const OP_COUNT: usize = 45;',
        'pub const ARG_COUNTS: [usize; OP_COUNT] = ['+','.join(str(len(o['arguments'])) for o in operations)+'];',
        'pub const WIDE_MASKS: [u16; OP_COUNT] = ['+','.join(str(sum(1<<i for i,t in enumerate(o['arguments']) if t in 'UI')) for o in operations)+'];']
    for op in operations:
        types=op['arguments']
        if any(t not in 'upUI' for t in types) or len(types)>9: raise ValueError('invalid signature')
        params=', '.join(('uint64_t' if t in 'UI' else 'uint32_t')+f' a{i}' for i,t in enumerate(types)) or 'void'
        result='void' if op['noreturn'] else 'uint32_t'
        c.append(f'{result} __imported_wasi_snapshot_preview1_{op["name"]}({params}) {{')
        if types: c.append('    const uint64_t args[] = {'+', '.join(f'a{i}' for i in range(len(types)))+'};')
        expr=f'call({op["opcode"]}u, '+('args' if types else 'NULL')+f', {len(types)}u)'
        c.append('    (void)'+expr+'; __builtin_trap();' if op['noreturn'] else '    return '+expr+';')
        c.append('}')
        rs.append(f'pub const {op["name"].upper()}: u32 = {op["opcode"]};')
    header='#ifndef DOTNET_PAL_WASI_SCHEMA_H\n#define DOTNET_PAL_WASI_SCHEMA_H\n' + ''.join(f'#define DOTNET_PAL_WASI_{o["name"].upper()} {o["opcode"]}u\n' for o in operations) + '#endif\n'
    return {'crates/dotnet-pal-build/native/wasi_schema.h':header, 'crates/dotnet-pal-build/native/wasi_bridge.c':'\n'.join(c)+'\n','src/wasi_schema.rs':'\n'.join(rs)+'\n'}
def main():
    parser=argparse.ArgumentParser(); parser.add_argument('--check',action='store_true'); args=parser.parse_args()
    for path,text in outputs().items():
        if args.check:
            if not (ROOT/path).exists() or (ROOT/path).read_text()!=text: raise SystemExit(f'stale generated file: {path}')
        else: (ROOT/path).write_text(text)
if __name__=='__main__': main()
