[package]
name = "dotnet-pal-linux-std"
version = "0.7.0"
edition = "2021"
rust-version = "1.98"
description = "linux PAL port on the Rust standard library"
license = "MIT"
repository = "https://github.com/hckaye/dotnet-pal-rs"
include = ["src/**", "Cargo.toml", "README.md", "LICENSE", "native/**"]

[features]
default = []
entry = []
[dependencies]
dotnet-pal-rs = { version = "0.7.0", path = "../..", default-features = false }
dotnet-pal-std-common = { version = "0.7.0", path = "../dotnet-pal-std-common" }
getrandom = "0.3"
socket2 = "0.5"
libc = "0.2"
